name: "tauri publish"
on:
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "pnpm"
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install Dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libsoup-3.0-dev libjavascriptcoregtk-4.1-dev
      - name: Install Frontend Dependencies
        run: pnpm i
      - name: Set environment variables
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            $BRANCH_NAME=$env:GITHUB_REF.Replace('refs/heads/', '')
            $SHORT_SHA=$(git rev-parse --short HEAD)
            echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
            echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          else
            BRANCH_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
            SHORT_SHA=$(git rev-parse --short HEAD)
            echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
            echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          fi
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: "client-${{ env.BRANCH_NAME }}_${{ env.SHORT_SHA }}"
          releaseName: "Spacebar Client ${{ env.BRANCH_NAME }}_${{ env.SHORT_SHA }}"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: false
          prerelease: true
